package com.example.TCBA.Exception;

public enum ErrorCode {

    // AUTH
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    FORBIDDEN,
    ACCOUNT_INACTIVE,

    // MPIN
    MPIN_NOT_SET,
    INVALID_MPIN,
    MPIN_INVALID,
    MPIN_LAST_ATTEMPT,
    MPIN_LOCKED,
    MPIN_MISMATCH,
    MPIN_SAME_AS_OLD,


    // OTP
    OTP_INVALID,
    OTP_EXPIRED,

    // PASSWORD
    PASSWORD_MISMATCH,

    // WALLET / PAYMENT
    INSUFFICIENT_BALANCE,
    PAYMENT_REQUIRED,
    DUPLICATE_TRANSACTION,

    // COMMON
    BAD_REQUEST,
    INTERNAL_ERROR,

    // WALLET
    WALLET_NOT_FOUND,
    WALLET_BLOCKED,

    //YARD
    YARD_NOT_FOUND,
    NOT_A_YARD,

    //PAYMENT
    NOT_A_INSTANT_USER,
}

